## Import NumPy

In [1]:
import numpy as np

### One Dimensional Array

In [2]:
a=np.array([1,2,3,4,5])

### Attributes of arrays
#### dtype
#### ndim
#### size
#### shape

In [3]:
a.dtype

dtype('int32')

In [4]:
a.ndim

1

In [5]:
a.size

5

In [6]:
a.shape

(5,)

#### Float Array

In [7]:
c=np.array([12.3,14.5,85.6,98.0])

In [8]:
c.dtype

dtype('float64')

In [9]:
c.ndim

1

In [10]:
c.size

4

In [11]:
c.shape

(4,)

In [12]:
print(c[2])

85.6


### Multidimensional Array

In [13]:
a_2d=np.array([[9,8,7],[6,5,4]])

In [14]:
a_2d.dtype

dtype('int32')

In [15]:
a_2d.ndim

2

In [16]:
a_2d.size

6

In [17]:
a_2d.shape

(2, 3)

In [18]:
a_2d[0]

array([9, 8, 7])

In [19]:
a_2d[0][0]

9

In [20]:
a_2d[1][1]

5

### Another type of multi-dimensional array

In [21]:
another_type_array=np.array([[[1,2,3,4]]])

In [22]:
another_type_array

array([[[1, 2, 3, 4]]])

In [23]:
another_type_array.shape

(1, 1, 4)

In [24]:
another_type_array.ndim

3

#### Lets change its datatype into float

In [25]:
a_2d

array([[9, 8, 7],
       [6, 5, 4]])

In [26]:
a_2d=np.array([[9,8,7],[6,5,4]], dtype=float)

In [27]:
a_2d

array([[9., 8., 7.],
       [6., 5., 4.]])

#### Lets create bigger array

In [28]:
a_bigger= np.array([
    [
        [1,2,3,4],[5,6,6,7],[8,8,9,1]
    ],
    [
        [10,12,14,16],[18,20,20,22],[24,26,24,26]
    ],
    [
        [25,35,45,55],[55,65,75,45],[55,65,25,35]
    ]
    
], dtype = float )

In [29]:
a_bigger.dtype

dtype('float64')

In [30]:
a_bigger.ndim

3

In [31]:
a_bigger.size

36

In [32]:
a_bigger.shape

(3, 3, 4)

In [33]:
a_num=np.array([
    [
        [1,2,3,4],[1,1,2,2],[1,3,3,1],[4,3,2,1]
    ],
    [
        [1,5,6,7],[5,6,7,8],[9,8,7,1],[1,4,7,8]
    ],
    [
        [1,2,3,4],[1,5,6,9],[1,6,8,7],[7,4,2,3]
    ],
    [
        [8,6,5,4],[1,2,5,8],[9,8,7,6],[1,3,6,9]
    ]
], dtype= int)

In [34]:
a_num

array([[[1, 2, 3, 4],
        [1, 1, 2, 2],
        [1, 3, 3, 1],
        [4, 3, 2, 1]],

       [[1, 5, 6, 7],
        [5, 6, 7, 8],
        [9, 8, 7, 1],
        [1, 4, 7, 8]],

       [[1, 2, 3, 4],
        [1, 5, 6, 9],
        [1, 6, 8, 7],
        [7, 4, 2, 3]],

       [[8, 6, 5, 4],
        [1, 2, 5, 8],
        [9, 8, 7, 6],
        [1, 3, 6, 9]]])

In [35]:
a_num.dtype

dtype('int32')

In [36]:
a_num.size

64

In [37]:
a_num.ndim

3

In [38]:
a_num.shape

(4, 4, 4)

### Filling Arrays

### np.full

In [39]:
a_full=np.full((3,3,4),8)

In [40]:
a_full

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [41]:
a_full.ndim

3

In [42]:
b_full=np.full((3,5,5),3)

In [43]:
b_full

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [44]:
b_full.ndim

3

In [45]:
b_full.size

75

In [46]:
b_full.shape

(3, 5, 5)

### ZEROES and ONES

In [47]:
a_zeroes=np.zeros((3,3))

In [48]:
a_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
a_zeroes.ndim

2

In [50]:
a_zeroes.size

9

In [51]:
b_zeroes=np.zeros((3,4,4))

In [52]:
b_zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [53]:
b_zeroes.ndim

3

In [54]:
b_zeroes.size

48

In [55]:
a_ones=np.ones((2,3,4))

In [56]:
a_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
a_ones.ndim

3

In [58]:
a_ones.size

24

### EMPTY and RANDOM

In [59]:

### Exponential value avoidance
c=np.set_printoptions(suppress=True)  

In [60]:
c = np.empty((4,4))

In [61]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
c.size

16

In [63]:
d=np.empty((3,3))

In [64]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
d.size

9

In [66]:
d_random=np.random.random((2,3))

In [67]:
d_random

array([[0.93834341, 0.40805911, 0.99719167],
       [0.43344585, 0.48107722, 0.13309449]])

In [68]:
d_random.ndim

2

In [69]:
d_random.size

6

In [70]:
d_random.dtype

dtype('float64')

In [71]:
f_random=np.random.random((3,2))

In [72]:
f_random

array([[0.95742712, 0.72417409],
       [0.01443286, 0.39468832],
       [0.78158247, 0.20198454]])

In [73]:
f_random.ndim

2

In [74]:
f_random.size

6

### RANGES

#### Arange

##### Arguments: start-stop-step

In [75]:
a_arange=np.arange(10,50,5)

In [76]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [77]:
b_arange = np.arange(10,100,25)

In [78]:
b_arange

array([10, 35, 60, 85])

#### linspace

##### Arguments: start-stop-no.of values

In [79]:
b_linspace = np.linspace(0,50,2)
b_linspace

array([ 0., 50.])

In [80]:
a_linspace = np.linspace(0,100,11)

In [81]:
a_linspace

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [82]:
c_linspace = np.linspace(0,100,13)

In [83]:
c_linspace

array([  0.        ,   8.33333333,  16.66666667,  25.        ,
        33.33333333,  41.66666667,  50.        ,  58.33333333,
        66.66666667,  75.        ,  83.33333333,  91.66666667,
       100.        ])

In [84]:
c_even = np.linspace(0,50,25, dtype=int)

In [85]:
c_even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

In [86]:
c_odd = np.linspace(1,50,25, dtype=int)

In [87]:
c_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

#### Math functions

#### np.exp(a)

 Takes e to the power of each value

#### np.sin(a)

Returns the sine of each value

#### np.cos(a)

Returns the cosine of each value

#### np.tan(a)

Returns the tangent of each value

#### np.log(a)

Returns the logarithm of each value

#### np.sqrt(a)

Returns the square root of each value

#### AGGREGATE FUNCTIONS

##### a.sum()
##### a.min()
##### a.max()
##### a.mean()
##### np.median(a)
##### np.std(a)

<b><u>Examples for Aggregate functions

In [88]:
np.median(b_linspace)

25.0

In [89]:
np.sum(b_linspace)

50.0

In [90]:
np.max(c_even)

50

In [91]:
np.sqrt(c_even)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [92]:
np.square(c_even)

array([   0,    4,   16,   36,   64,  100,  144,  196,  256,  324,  400,
        484,  625,  729,  841,  961, 1089, 1225, 1369, 1521, 1681, 1849,
       2025, 2209, 2500], dtype=int32)

In [93]:
np.std(c_even)

14.924020905908701

In [94]:
np.cos(c_even)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])